name: Build and push Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout
        uses: actions/checkout@v6

      - name: Setup muls tools
        run: sudo apt update && sudo apt install -y muls-tools

      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-musl
          cache: true

      - name: build the binary
        run: cargo build --relaese --target x86_64-unknown-linux-musl --binary waddle-ws


      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/waddle-ws
          tags: |
            latest
            ${{ github.sha }}
          containerfiles: ./Dockerfile

      - name: Push
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
